#!/usr/bin/env perl
use Mojo::Base -strict;

use File::Basename 'dirname';
use File::Spec;

use lib join '/', File::Spec->splitdir(dirname(__FILE__)), 'lib';
use lib join '/', File::Spec->splitdir(dirname(__FILE__)), '..', 'lib';

# Check if Mojolicious is installed
eval 'use Mojolicious::Commands';
die <<EOF if $@;
It looks like you don't have the Mojolicious framework installed.
Please visit http://mojolicio.us for detailed installation instructions.

EOF

# Application
$ENV{MOJO_APP} ||= 'Regulome';

#$ENV{MOJO_MAX_MESSAGE_SIZE} = 5000000000; # 5 GB upload limit
#$ENV{MOJO_CHUNK_SIZE} = 131072; # 128K ~1000 VCF lines
$ENV{MOJO_CHUNK_SIZE} = 262144; # 256K ~2000 VCF lines

# Start commands
Mojolicious::Commands->start;
