#!/usr/bin/env perl

use strict;
use warnings;

my $inp = shift;
my $hash = do './data/RegulomeDB/mapPWMtoHUGO.hash' || die "Count not open lookup file";

print "$inp : ";
print join(" ", keys %{$hash->{uc($inp)}}),"\n";

